label: 'ማን ነው አዲስ'
display:
  default:
    display_title: ነባሪ
    display_options:
      title: 'ማን ነው አዲስ'
      exposed_form:
        options:
          exposed_sorts_label: ደርድር
  block_1:
    display_title: 'ማን ነው አዲስ'
    display_options:
      block_description: 'ማን ነው አዲስ'
      block_category: ተጠቃሚ
