display:
  default:
    display_title: ነባሪ
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: ደርድር
  block_1:
    display_title: ጥምር
  page_1:
    display_title: ገጽ
