label: 'Kontaktiere uns'
reply: 'Vielen Dank für Ihr Interesse. Einer unserer Vertreter wird Sie bald erreichen.'
message: 'Vielen Dank für Ihr Interesse. Einer unserer Vertreter wird Sie bald erreichen.'
